name: env_R10_VerdeClaro
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch         
  - torchvision
  - torchaudio
  - pip:
      - pyspark
      - psycopg2-binary  
      - pandas
      - matplotlib
      - networkx
      - torch-geometric  
      - ipykernel